---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}-build
  namespace: ${{ values.argocd_namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    rhdh-demo/application: ${{ values.component_id }}
spec:
  project: default
  source:
    repoURL: ${{ values.destination }}
    targetRevision: HEAD
    path: ./helm/build
    helm:
      valueFiles:
        - Values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.component_id }}-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m