apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: demo
  namespace: ${RHDH_NAMESPACE}
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    extraEnvs:
      secrets:
        - name: rhdh-secrets
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
  deployment:
    patch:
      spec:
        template:
          spec:
            containers:
              - envFrom:
                  - secretRef:
                      name: llama-stack-secrets
                image: 'quay.io/redhat-ai-dev/llama-stack:0.1.1'
                name: llama-stack
                volumeMounts:
                  - mountPath: /app-root/.llama
                    name: shared-storage
                  - mountPath: /app-root/embeddings_model
                    name: rag-data-volume
                    subPath: embeddings_model
                  - mountPath: /app-root/vector_db/rhdh_product_docs
                    name: rag-data-volume
                    subPath: rhdh_product_docs
              - image: 'quay.io/lightspeed-core/lightspeed-stack:dev-20251021-ee9f08f'
                name: lightspeed-core
                volumeMounts:
                  - mountPath: /app-root/lightspeed-stack.yaml
                    name: lightspeed-stack
                    subPath: lightspeed-stack.yaml
                  - mountPath: /tmp/data/feedback
                    name: shared-storage
                  - mountPath: /tmp/data/transcripts
                    name: shared-storage
                  - mountPath: /tmp/data/conversations
                    name: shared-storage
            initContainers:
                - command:
                    - sh
                    - '-c'
                    - echo 'Copying RAG data...'; cp -r /rag/vector_db/rhdh_product_docs /data/ && cp -r /rag/embeddings_model /data/ && echo 'Copy complete.'
                  image: 'quay.io/redhat-ai-dev/rag-content:release-1.8-lcs'
                  name: init-rag-data
                  volumeMounts:
                    - mountPath: /data
                      name: rag-data-volume
            volumes:
              - configMap:
                  name: lightspeed-stack
                name: lightspeed-stack
              - emptyDir: {}
                name: shared-storage
              - emptyDir: {}
                name: rag-data-volume
              - name: dynamic-plugins-root
                "$patch": replace
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root
