kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
  namespace: ${RHDH_NAMESPACE}
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      # GitHub Org Catalog Backend
      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org-dynamic
        disabled: false

      # JFrog Artifactory
      - package: ./dynamic-plugins/dist/backstage-community-plugin-jfrog-artifactory
        disabled: false

      # Quay Plugin
      - package: ./dynamic-plugins/dist/backstage-community-plugin-quay
        disabled: false

      # Tech Radar
      - package: ./dynamic-plugins/dist/backstage-community-plugin-tech-radar
        disabled: false

      # Jira Plugin
      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-jira
        disabled: false

      # ArgoCD Backend
      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd-backend-dynamic
        disabled: false
      # ArgoCD Frontend (Red Hat)
      - package: ./dynamic-plugins/dist/backstage-community-plugin-redhat-argocd
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage-community.plugin-redhat-argocd:
                mountPoints:
                  - mountPoint: entity.page.overview/cards
                    importName: ArgocdDeploymentSummary
                    config:
                      layout:
                        gridColumnEnd:
                          lg: span 8
                          xs: span 12
                      if:
                        allOf:
                          - isArgocdConfigured
                  - mountPoint: entity.page.cd/cards
                    importName: ArgocdDeploymentLifecycle
                    config:
                      layout:
                        gridColumn: 1 / -1
                      if:
                        allOf:
                          - isArgocdConfigured

      # Topology Plugin
      - package: ./dynamic-plugins/dist/backstage-community-plugin-topology
        disabled: false

      # Tekton Plugin
      - package: ./dynamic-plugins/dist/backstage-community-plugin-tekton
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage-community.plugin-tekton:
                mountPoints:
                  - mountPoint: entity.page.ci/cards
                    importName: TektonCI
                    config:
                      layout:
                        gridColumn: 1 / -1
                      if:
                        allOf:
                          - isTektonCIAvailable

      # Kubernetes Frontend
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage.plugin-kubernetes:
                mountPoints:
                  - mountPoint: entity.page.kubernetes/cards
                    importName: EntityKubernetesContent
                    config:
                      layout:
                        gridColumn: 1 / -1
                      if:
                        anyOf:
                          - hasAnnotation: backstage.io/kubernetes-id
                          - hasAnnotation: backstage.io/kubernetes-namespace

      # Kubernetes Backend
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
        disabled: false

      # Scaffolder Kubernetes Module
      - package: ./dynamic-plugins/dist/backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic
        disabled: true

      # Scaffolder GitHub Module
      - package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic
        disabled: false

      # Scaffolder ArgoCD Module
      - package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-argocd-dynamic
        disabled: false

      # Lightspeed plugins
      - disabled: false
        package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-lightspeed:bs_1.42.5__1.0.3!red-hat-developer-hub-backstage-plugin-lightspeed
        pluginConfig:
          dynamicPlugins:
            frontend:
              red-hat-developer-hub.backstage-plugin-lightspeed:
                translationResources:
                  - importName: lightspeedTranslations
                    module: Alpha
                    ref: lightspeedTranslationRef
                appIcons:
                  - name: LightspeedIcon
                    module: LightspeedPlugin
                    importName: LightspeedIcon
                dynamicRoutes:
                  - path: /lightspeed
                    importName: LightspeedPage
                    module: LightspeedPlugin
                    menuItem:
                      icon: LightspeedIcon
                      text: Lightspeed
      - disabled: false
        package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-lightspeed-backend:bs_1.42.5__1.0.3!red-hat-developer-hub-backstage-plugin-lightspeed-backend

      # MCP servers
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-mcp-actions-backend:bs_1.42.5__0.1.2!backstage-plugin-mcp-actions-backend
        disabled: false
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-software-catalog-mcp-tool:bs_1.42.5__0.2.3!red-hat-developer-hub-backstage-plugin-software-catalog-mcp-tool
        disabled: false
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-techdocs-mcp-tool:bs_1.42.5__0.3.0!red-hat-developer-hub-backstage-plugin-techdocs-mcp-tool
        disabled: false
      
      # Github issues
      - package: ./dynamic-plugins/dist/backstage-community-plugin-github-issues
        disabled: false

      # Github pull requests
      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-github-pull-requests
        disabled: false
  
  
      # Github actions
      - package: ./dynamic-plugins/dist/backstage-community-plugin-github-actions
        disabled: false

      # Bulk Import
      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-bulk-import
        disabled: true


      # Homepage
      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-dynamic-home-page
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              red-hat-developer-hub.backstage-plugin-dynamic-home-page:
                dynamicRoutes:
                - path: /
                  importName: DynamicCustomizableHomePage
                mountPoints:
                - mountPoint: application/listener
                  importName: VisitListener
                - mountPoint: home.page/cards
                  importName: OnboardingSection
                  config:
                    id: rhdh-onboarding-section
                    title: Red Hat Developer Hub - Onboarding
                    cardLayout:
                      width:
                        minColumns: 4
                        maxColumns: 12
                        defaultColumns: 12
                      height:
                        minRows: 2
                        maxRows: 12
                        defaultRows: 4
                    layouts:
                      xl:
                        w: 12
                        h: 6
                      lg:
                        w: 12
                        h: 6
                      md:
                        w: 12
                        h: 7
                      sm:
                        w: 12
                        h: 8
                      xs:
                        w: 12
                        h: 9
                      xxs:
                        w: 12
                        h: 14
                - mountPoint: home.page/cards
                  importName: EntitySection
                  config:
                    id: rhdh-entity-section
                    title: Red Hat Developer Hub - Software Catalog
                    cardLayout:
                      width:
                        minColumns: 4
                        maxColumns: 12
                        defaultColumns: 12
                      height:
                        minRows: 2
                        maxRows: 12
                        defaultRows: 4
                    layouts:
                      xl:
                        w: 12
                        h: 7
                      lg:
                        w: 12
                        h: 7
                      md:
                        w: 12
                        h: 8
                      sm:
                        w: 12
                        h: 9
                      xs:
                        w: 12
                        h: 11
                      xxs:
                        w: 12
                        h: 15
                - mountPoint: home.page/cards
                  importName: TemplateSection
                  config:
                    id: rhdh-template-section
                    title: Red Hat Developer Hub - Explore templates
                    cardLayout:
                      width:
                        minColumns: 4
                        maxColumns: 12
                        defaultColumns: 12
                      height:
                        minRows: 2
                        maxRows: 12
                        defaultRows: 4
                    layouts:
                      xl:
                        w: 12
                        h: 5
                      lg:
                        w: 12
                        h: 5
                      md:
                        w: 12
                        h: 5
                      sm:
                        w: 12
                        h: 5
                      xs:
                        w: 12
                        h: 7.5
                      xxs:
                        w: 12
                        h: 13.5
                - mountPoint: home.page/cards
                  importName: QuickAccessCard
                  config:
                    id: quickaccess-card
                    title: Quick Access Card
                - mountPoint: home.page/cards
                  importName: SearchBar
                  config:
                    id: searchbar
                    title: Search
                    cardLayout:
                      width:
                        minColumns: 4
                        maxColumns: 12
                        defaultColumns: 12
                      height:
                        minRows: 1
                        maxRows: 2
                        defaultRows: 2
                - mountPoint: home.page/cards
                  importName: CatalogStarredEntitiesCard
                  config:
                    id: catalog-starred-entities-card
                    title: Starred catalog entities
                - mountPoint: home.page/cards
                  importName: RecentlyVisitedCard
                  config:
                    id: recently-visited-card
                    title: Recently visited
                - mountPoint: home.page/cards
                  importName: TopVisitedCard
                  config:
                    id: top-visited-card
                    title: Top visited
                - mountPoint: home.page/cards
                  importName: FeaturedDocsCard
                  config:
                    id: featured-docs-card
                    title: Featured docs
                - mountPoint: home.page/cards
                  importName: JokeCard
                  config:
                    id: joke-card
                    title: Random joke
                translationResources:
                - importName: homepageTranslations
                  ref: homepageTranslationRef